import Link from 'next/link';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import Image from 'next/image';

import { Button, Col, Container, Row, Dropdown, DropdownItem, DropdownToggle, DropdownMenu } from "react-bootstrap";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="wrapper">
          <header>
            <div className="header">
              <Link href="/" passHref className="logo">
                <Image
                  src="/courseseeker_logo.svg"
                  width={500}
                  height={500}
                  alt="Courseseeker logo"
                />
              </Link>
              <Link href="/" passHref>
                Home
              </Link>
              <Link href="/courses/browse" passHref>
                Courses</Link>
              <div className="find-course">
                <input type="text" className="form-control" placeholder="Find course..."></input>
              </div>
              <Dropdown className="ms-auto">
                <DropdownToggle variant="secondary" id="dropdown-basic">
                  Name Surname
                </DropdownToggle>
                <DropdownMenu variant="dark">
                  <DropdownItem href="#/action-1">Profile</DropdownItem>
                  <DropdownItem href="#/action-2">Settings</DropdownItem>
                  <DropdownItem href="#/action-3">Exit</DropdownItem>
                </DropdownMenu>
              </Dropdown>
            </div>
          </header>
          <div className="main">
            {children}
          </div>
          <footer>
            le footer trademark
          </footer>
        </div>
      </body>
    </html>
  );
}
